//go:build bazel_ui_archive

// Package webassets embeds the renderer generated by the declared Bazel Vite
// action. It intentionally has no JavaScript runtime dependency.
package webassets

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"embed"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"path"
	"strings"
	"sync"
	"testing/fstest"
)

//go:embed ui-dist.tar.gz
var Files embed.FS

var (
	assetsOnce sync.Once
	assetsFS   fs.FS
	assetsErr  error
)

func loadAssets() {
	archive, err := Files.ReadFile("ui-dist.tar.gz")
	if err != nil {
		assetsErr = fmt.Errorf("read embedded UI archive: %w", err)
		return
	}
	gzipReader, err := gzip.NewReader(bytes.NewReader(archive))
	if err != nil {
		assetsErr = fmt.Errorf("open embedded UI archive: %w", err)
		return
	}
	defer gzipReader.Close()

	tarReader := tar.NewReader(gzipReader)
	files := fstest.MapFS{}
	for {
		header, err := tarReader.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			assetsErr = fmt.Errorf("read embedded UI archive: %w", err)
			return
		}
		switch header.Typeflag {
		case tar.TypeDir:
			continue
		case tar.TypeReg, tar.TypeRegA:
			name := strings.TrimPrefix(path.Clean(header.Name), "./")
			if name == "" || name == "." || !fs.ValidPath(name) {
				assetsErr = fmt.Errorf("embedded UI archive has unsafe path %q", header.Name)
				return
			}
			contents, err := io.ReadAll(tarReader)
			if err != nil {
				assetsErr = fmt.Errorf("read embedded UI asset %q: %w", name, err)
				return
			}
			files[name] = &fstest.MapFile{Data: contents, Mode: fs.FileMode(header.Mode)}
		default:
			assetsErr = fmt.Errorf("embedded UI archive has unsupported entry %q", header.Name)
			return
		}
	}
	if _, ok := files["index.html"]; !ok {
		assetsErr = fmt.Errorf("embedded UI archive is missing index.html")
		return
	}
	assetsFS = files
}

// FS returns the generated Vite distribution rooted at its index.html.
func FS() (fs.FS, error) {
	assetsOnce.Do(loadAssets)
	return assetsFS, assetsErr
}

// Handler serves static files and applies an SPA fallback only to route-like
// paths. Missing asset URLs intentionally return 404 instead of index.html.
func Handler() http.Handler {
	assets, err := FS()
	if err != nil {
		return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			http.Error(w, "embedded web assets are unavailable", http.StatusServiceUnavailable)
		})
	}
	files := http.FileServer(http.FS(assets))
	serveIndex := func(w http.ResponseWriter, r *http.Request) {
		http.ServeFileFS(w, r, assets, "index.html")
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		candidate := strings.TrimPrefix(path.Clean("/"+r.URL.Path), "/")
		if candidate == "" || candidate == "." {
			serveIndex(w, r)
			return
		}
		if _, err := fs.Stat(assets, candidate); err == nil {
			files.ServeHTTP(w, r)
			return
		}
		if strings.Contains(path.Base(candidate), ".") {
			http.NotFound(w, r)
			return
		}
		serveIndex(w, r)
	})
}
